language: node_js
node_js:
  - stable
deploy:
  provider: heroku
  app: app-shareyourideas-nodejs
  api_key:
    secure: Xmqk4gjXHp9IILQHmGlpfDwuB+gLnrwW4m7tuxHVguT3+x4pmoc+QhjujuF3xXH3OGhthhcQigqfAFC87CAfEFB7WMlhZpE4p+SnWGVXBfJ950iuhqe/rXHpx940JxZNzXqLEKta7CHvOqP50/Xb0oBoSCEYqTsxcayyEmuGvAAboWaCRr9+6vCT78JK81pp1Bun02vaN5xXvZo/IphBi/gOZ/Hthgs/HjZF4or6ZejigGdWkGk6DmiE/c5X/enTzXApwuoDowvvhv1w+5ArlpVDuoUQuab8eDjFe6+C+QA6uBQYuFvmTuEn7q7zFSKEHuGt5D54jCdVI+EA7VHNDw2khiOVfZ2BEx0P1eOBwx5qW2GTSy2a3oETRBK9lSouabBWIz6aLgujF2eWEybZSlggKyrxBMawla7LCRgBEPg+FLgyEpq6TGLoQUq0Y+SOZJAQ7dhH6IP1S1sh5D2hckoOvFbyI0S12jv7A8073GdDU7r66WrfIPJ9h7d16UAJgYEuBzRvOHcUOwqG69/bExS+bzVSEwpZyRb+mFgKyyxkAyyfnuDweM47CH1TUqlFvpMEaYg9l1VERKh9F524Gh9Kiwc/IZrE/QwgKEMyMQrwdEcJKl30F8QcbTmI83ngt8528NmvmkcObJu8SF/HmLaOxjlFMNNvT4jH+UsScr0=